### ISSUE TITLE
malformed footer on the new Reddit

### ISSUE THREAD

**Issue by MatthewDaffern** [Nokeo08/standardsbot#16]
Hey man, It's I_need_to_argue. Your footer on the bot has partially broken markdown formatting on this [comment](https://www.reddit.com/r/Reformed/comments/97wbyp/standardsbot_updated_to_v188/e4bg8aw). It was a pain in the butt to get working on my scripturebot test because now Reddit "helps" with markdown formatting, but basically there's some escape slashes probably getting inserted somewhere in the comment when the bot goes to post.

**Comment by Nokeo08** [comment]
Thanks for letting me know. I have a browser plugin that auto redirects me to old reddit so I would not have come across this. Were you able to fix it in your bot test?

**Comment by Nokeo08** [comment]
Fixed in PR #17. This will be live later today.

**Comment by MatthewDaffern** [comment]
Sound good. I think I got it working, but I'm not entirely sure. Man, the "fancy pants" editor is really annoying.

**Comment by Nokeo08** [comment]
The fix was to put parens around the word(s) being super scripted.

[Here's a link to the diff](https://github.com/Nokeo08/standardsbot/pull/17/commits/77666f503d2c9a5a3ed3508528e481245857c9cd)

**Comment by MatthewDaffern** [comment]
Thanks! I'll be using you for inspiration if my solution doesn't end up
working. I pretty much did the same thing for scripturebot.
