### ISSUE TITLE
Westminster misspelled in header of a citation

### ISSUE THREAD

**Issue by Nokeo08** [Nokeo08/standardsbot#4]
Both WLC and WSC are missing a second t.

**Comment by anotherdude1** [comment]
I see in parser.py the Wesminster typo. Maybe fixing in that file will fix the typo?

http://i.imgur.com/x8MTLYG.jpg

**Comment by Nokeo08** [comment]
Yeah, That is the issue. Just haven't had the time to fix it. Still getting caught up with work.

**Comment by anotherdude1** [comment]
Thanks! If I can help you in anyway, let me know. I'm not a programmer, but I enjoy learning about it and tinkering with things like this when I can find the time.

Grace and peace.
